---
- name: 'Create timer for backup: {{ backup.name }}'
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: 'backup-{{ backup.name | mandatory }}'
    systemd_timer_description: 'Backup of {{ backup.name | mandatory }} with Restic'
    systemd_timer_user: '{{ restic_user_name }}'
    systemd_timer_work_dir: '{{ restic_repo_path }}'
    systemd_timer_frequency: '{{ backup.frequency | default(restic_backup_default_frequency) }}'
    systemd_timer_timeout_sec: '{{ backup.timeout | default(restic_backup_default_timeout) }}'
    systemd_timer_requires_extra: '{{ backup.requires | default([]) }}'
    systemd_timer_after_extra: '{{ backup.after | default([]) }}'
    systemd_timer_start_on_creation: false
    systemd_timer_script_path: '{{ restic_binary_path }}'
    systemd_timer_script_args: >-
      backup --tag {{ backup.tags | default([]) | join("\n") }}
      {% for exclude in backup.get("excludes", []) %}
      --exclude '{{ exclude }}'
      {% endfor %}
      {{ backup.path | mandatory }}
    systemd_timer_environment:
      RESTIC_REPOSITORY: '{{ restic_repo_path }}'
      RESTIC_PASSWORD_FILE: '{{ restic_repo_pass_file }}'

- name: Create backup checks script
  template:
    src: 'check.sh.j2'
    dest: '/usr/local/bin/check-restic-{{ backup.name }}'
    mode: 0755

- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: 'restic_backup_{{ backup.name }}'
    consul_services:
      - id: 'restic-backup-{{ backup.name }}'
        name: 'restic-backup'
        tags: ['backup', 'restic']
        address: '{{ ansible_local.tinc.vpn_ip }}'
        meta:
          backup_repo: '{{ restic_repo_path }}'
          backup_name: '{{ backup.name }}'
          backup_path: '{{ backup.path }}'
          backup_tags: '{{ backup.tags | join(",") }}'
          backup_frequency: '{{ backup.frequency }}'
        checks:
          - id: 'restic-backup-check-{{ backup.name }}'
            name: 'Restic Backup Check'
            type: 'script'
            script: '/usr/local/bin/check-restic-{{ backup.name }}'
