---
- name: 'Create timer for backup: {{ backup.name }}'
  include_role: name=infra-role-systemd-timer
  vars:
    systemd_timer_name:             'backup-{{ backup.name | mandatory }}'
    systemd_timer_description:      'Backup of {{ backup.name | mandatory }} with Restic'
    systemd_timer_documentation:    '{{ backup.docs            | default(restic_backup_default_docs_url) }}'
    systemd_timer_frequency:        '{{ backup.frequency       | default(restic_backup_default_frequency) }}'
    systemd_timer_timeout_sec:      '{{ backup.timeout         | default(restic_backup_default_timeout) }}'
    systemd_timer_restart:          '{{ backup.restart         | default(restic_backup_default_restart) }}'
    systemd_timer_restart_delay:    '{{ backup.restart_delay   | default(restic_backup_default_restart_delay) }}'
    systemd_timer_restart_retries:  '{{ backup.restart_retries | default(restic_backup_default_restart_retries) }}'
    systemd_timer_requires_extra:   '{{ backup.requires        | default(None) }}'
    systemd_timer_after_extra:      '{{ backup.after           | default(None) }}'
    systemd_timer_enabled:          '{{ backup.enabled         | default(True) }}'
    systemd_timer_user:             '{{ restic_user_name }}'
    systemd_timer_start_on_creation: false

    # Script Configuration
    systemd_timer_work_dir: '{{ restic_repo_path }}'
    systemd_timer_script_path: '{{ restic_binary_path }}'
    systemd_timer_exec_start_pre: ['{{ restic_backup_size_check_script }} {{ backup.path | join("") }}']
    systemd_timer_script_args: >-
      backup --tag {{ backup.tags | default([]) | join("\n") }}
      {% for exclude in backup.get("excludes", []) %}
      --exclude '{{ exclude }}'
      {% endfor %}
      {{ backup.path | mandatory }}
    systemd_timer_environment:
      RESTIC_REPOSITORY: '{{ restic_repo_path }}'
      RESTIC_PASSWORD_FILE: '{{ restic_repo_pass_file }}'
      RESTIC_CACHE_DIR: '{{ restic_cache_path }}'

    # Consul Definition & Check
    systemd_timer_consul_service_id: 'restic-backup-{{ backup.name }}'
    systemd_timer_consul_service_name: 'restic-backup'
    systemd_timer_consul_extra_tags: ['backup', 'restic']
    systemd_timer_consul_meta:
      version:          '{{ restic_version }}'
      backup_repo:      '{{ restic_repo_path }}'
      backup_name:      '{{ backup.name      | mandatory }}'
      backup_docs:      '{{ backup.docs      | default(restic_backup_default_docs_url) }}'
      backup_tags:      '{{ backup.tags      | join(",") }}'
      backup_path:      '{{ backup.path      | mandatory }}'
      backup_frequency: '{{ backup.frequency | default(restic_backup_default_frequency) }}'
      backup_enabled:   '{{ backup.enabled   | default(True) | string }}'
