---
- name: Make backup user owner of repo
  file:
    path: '{{ restic_repo_path }}'
    owner: '{{ restic_user_name }}'
    group: '{{ restic_user_name }}'
    state: 'directory'
    mode: 0700

- name: Change password of Restic repo
  when: |
    restic_repo_pass_old is defined and
    restic_repo_pass_old != restic_repo_pass
  command: |
    restic key passwd --new-password-file={{ restic_repo_pass_file }}
  become_user: '{{ restic_user_name }}'
  environment:
    RESTIC_REPOSITORY: '{{ restic_repo_path }}'
    RESTIC_PASSWORD_FILE: '{{ restic_repo_pass_file_copy.backup_file }}'
    RESTIC_CACHE_DIR: '{{ restic_cache_path }}'

- name: Initialize the Restic repo
  command:
    cmd: 'restic init'
    creates: '{{ restic_repo_path }}/snapshots'
  become_user: '{{ restic_user_name }}'
  environment:
    RESTIC_REPOSITORY: '{{ restic_repo_path }}'
    RESTIC_PASSWORD_FILE: '{{ restic_repo_pass_file }}'
    RESTIC_CACHE_DIR: '{{ restic_cache_path }}'

- name: Create backup size check script
  template:
    src:   'backup-check-script.sh.j2'
    dest:  '{{ restic_backup_size_check_script }}'
    owner: '{{ restic_user_name }}'
    group: '{{ restic_user_name }}'
    mode: 0775

- name: Create snapshot size check script
  template:
    src:   'snapshot-restic-check.sh.j2'
    dest:  '{{ restic_snapshot_check_script }}'
    owner: '{{ restic_user_name }}'
    group: '{{ restic_user_name }}'
    mode: 0775
