---
- name: Download Restic archive
  get_url:
    url: '{{ restic_bz2_url }}'
    dest: '/tmp/{{ restic_bz2 }}'
    checksum: 'sha256:{{ restic_bz2_sha256 }}'
    mode: 0644

- name: Unpack Restic archive
  shell: bzip2 -dc '/tmp/{{ restic_bz2 }}' > '{{ restic_binary_path }}'

- name: Adjust binary permissions
  file:
    path: '{{ restic_binary_path }}'
    mode: 0755

