---
- name: Create password file
  copy:
    dest:    '{{ restic_repo_pass_file }}'
    content: '{{ restic_repo_pass | mandatory }}'
    owner:   '{{ restic_user_name }}'
    group:   '{{ restic_user_name }}'
    mode:    0600
    # THIS IS VERY IMPORTANT IN CASE OF PASSWORD CHANGE
    backup: true
  register: restic_repo_pass_file_copy

# To simplify use with `sudo -iu restic ...`
- name: Create bashrc file
  copy:
    dest: '{{ restic_user_home }}/.bashrc'
    content: |
      export RESTIC_REPOSITORY='{{ restic_repo_path }}'
      export RESTIC_PASSWORD_FILE='{{ restic_repo_pass_file }}'
      export RESTIC_CACHE_DIR='{{ restic_cache_path }}'
    owner: '{{ restic_user_name }}'
    group: '{{ restic_user_name }}'
    mode: 0600
