---
- name: Create backup group
  group:
    name: '{{ restic_user_name }}'
    gid: '{{ restic_user_uid }}'

- name: Create backup user
  user:
    name: '{{ restic_user_name }}'
    uid: '{{ restic_user_uid }}'
    group: '{{ restic_user_name }}'
    groups: '{{ restic_user_groups }}'
    append: true
    create_home: true
    shell: '/bin/bash'

- name: Create ~/.ssh directory
  file:
    dest: '{{ restic_user_home }}/.ssh'
    owner: '{{ restic_user_name }}'
    group: '{{ restic_user_name }}'
    state: 'directory'
    mode: 0700
  when: restic_ssh_public_key is defined

# Limit SSH access to just SFTP
- name: Create authorized_keys file
  copy:
    dest: '{{ restic_user_home }}/.ssh/authorized_keys'
    content: 'command="/usr/lib/openssh/sftp-server" {{ restic_ssh_public_key | mandatory }}'
    owner: '{{ restic_user_name }}'
    group: '{{ restic_user_name }}'
    mode: 0640
  when: restic_ssh_public_key is defined
